name: Accessibility (pa11y-ci)
on:
  push:
  pull_request:
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install pa11y-ci
        run: npm install -g pa11y-ci

      - name: Serve site (static)
        run: |
          npm install -g serve
          serve -s . -l 5000 &
          sleep 2

      - name: Run pa11y-ci
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: '1'
        run: |
          printf '{"defaults":{"timeout":30000},"urls":["http://localhost:5000/"]}' > pa11y-ci.json
          pa11y-ci --config=pa11y-ci.json || true